# Generated by Django 4.1.2 on 2022-10-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('engine', models.CharField(max_length=40)),
                ('drive_type', models.CharField(max_length=40)),
                ('length', models.IntegerField()),
                ('generator', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
