# Generated by Django 4.1.2 on 2023-01-12 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('num_engines', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('engine', models.CharField(choices=[('1', 'D1-13'), ('2', 'D2-40'), ('3', 'D2-50'), ('4', 'D2-55'), ('5', 'D2-60'), ('6', 'D2-75'), ('7', 'D3-50'), ('8', 'D3-110'), ('9', 'D3-120'), ('10', 'D3-130'), ('11', 'D3-210'), ('12', 'D3-220'), ('13', 'D4-180'), ('14', 'D4-225'), ('15', 'D4-270'), ('16', 'D4-300'), ('17', 'D4-320'), ('19', 'D6-280'), ('20', 'D6-350'), ('21', 'D6-435'), ('22', 'D6-480'), ('23', 'D8A1'), ('24', 'D8A2'), ('25', 'D8A6'), ('26', 'D9A2'), ('27', 'D11A'), ('28', 'D11B'), ('29', 'D11C'), ('30', 'D13A'), ('31', 'D13B'), ('32', 'D13C')], default='1', max_length=40)),
                ('drive_type', models.CharField(choices=[('I', 'Inboard'), ('J', 'Jet Drive'), ('10A', 'IPS10-A'), ('15A', 'IPS15-A'), ('15B', 'IPS15-B'), ('15C', 'IPS15-C'), ('20D', 'IPS20-D'), ('20E', 'IPS20-E'), ('2A', 'IPS2-A'), ('2B', 'IPS2-B'), ('2C', 'IPS2-C'), ('30D', 'IPS30-D'), ('30E', 'IPS30-E'), ('3A', 'IPS3-A'), ('3C', 'IPS3-C'), ('A', 'IPS-A'), ('B', 'IPS-B'), ('C', 'IPS-D'), ('E', 'IPS-E'), ('F', 'IPS-F'), ('DA', 'DPH-A'), ('DC', 'DPH-C'), ('DD', 'DPH-D'), ('DD1', 'DPH-D1'), ('DE', 'DPH-E')], default='I', max_length=40)),
                ('length', models.IntegerField()),
                ('generator', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', multiselectfield.db.fields.MultiSelectField(choices=[('1', '3809721 Volvo 3809721 Fuel Filter'), ('2', 'A026K278 Onan A026K278 Fuel Filter'), ('3', 'E1C Camp E1C Engine Anode'), ('4', '2040N-30 Racor 2040N-30 Fuel Filter'), ('5', '2010PM-OR Racor 2010PM-OR Fuel Filter'), ('6', '838929 Engine Anode'), ('7', '10077K-SHW Sherwood Impeller Kit'), ('8', '21707132 Volvo 21707132 Oil Filter'), ('9', '0185-5835 Cummins 0185-5835 Oil Filter'), ('10', '93132 Star Brite 93132 Diesel Additive(32oz)'), ('11', '3556610 West Marine 3556610 - 60 Antifreeze(1 Gallon)'), ('12', '23219274 Volvo 23219274 Diesel Engine Oil(1 Gallon) 15w-40'), ('13', '23005191 Volvo 23005191 IPS Oil Filter'), ('14', '949656 Volvo 949656 O Ring'), ('15', '3593981 Volvo 3593981 Anode Kit'), ('16', '1141680 Volvo 1141680 Synthetic Gear Oil: 75W-90 (1 Gallon)'), ('17', '22030852 Volvo 22030852 Oil Filter'), ('18', '22030848 Volvo 22030848 Oil Filter'), ('19', '21718912 Volvo 21718912 Fuel Filter'), ('20', '3584145 Volvo 3584145 CCV Filter'), ('21', '21702999 Volvo 21702999 Air Filter Insert')], max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Service Date')),
                ('hours', models.IntegerField(verbose_name='Hours When Serviced')),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Engine Oil'), ('2', 'Drive Oil'), ('3', 'Fuel Filters'), ('4', 'Air Filters'), ('5', 'Impellers'), ('6', 'Engine Anodes'), ('7', 'Drive Anodes'), ('8', 'Hull Anodes'), ('9', 'Air Coolers'), ('10', 'Heat Exchangers'), ('11', 'Oil Samples'), ('12', 'Coolant Test'), ('13', 'Coolant Swap')], max_length=13)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.boat')),
            ],
            options={
                'ordering': ['hours'],
            },
        ),
        migrations.AddField(
            model_name='boat',
            name='parts',
            field=models.ManyToManyField(to='main_app.part'),
        ),
        migrations.AddField(
            model_name='boat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
