# Generated by Django 4.1.2 on 2022-10-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='num_engines',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='boat',
            name='drive_type',
            field=models.CharField(choices=[('I', 'Inboard'), ('J', 'Jet Drive'), ('10A', 'IPS10-A'), ('15A', 'IPS15-A'), ('15B', 'IPS15-B'), ('15C', 'IPS15-C'), ('20D', 'IPS20-D'), ('20E', 'IPS20-E'), ('2A', 'IPS2-A'), ('2B', 'IPS2-B'), ('2C', 'IPS2-C'), ('30D', 'IPS30-D'), ('30E', 'IPS30-E'), ('3A', 'IPS3-A'), ('3C', 'IPS3-C'), ('A', 'IPS-A'), ('B', 'IPS-B'), ('C', 'IPS-D'), ('E', 'IPS-E'), ('F', 'IPS-F'), ('DA', 'DPH-A'), ('DC', 'DPH-C'), ('DD', 'DPH-D'), ('DD1', 'DPH-D1'), ('DE', 'DPH-E')], default='I', max_length=40),
        ),
        migrations.AlterField(
            model_name='boat',
            name='engine',
            field=models.CharField(choices=[(1, 'D1-13'), (2, 'D2-40'), (3, 'D2-50'), (4, 'D2-55'), (5, 'D2-60'), (6, 'D2-75'), (7, 'D3-50'), (8, 'D3-110'), (9, 'D3-120'), (10, 'D3-130'), (11, 'D3-210'), (12, 'D3-220'), (13, 'D4-180'), (14, 'D4-225'), (15, 'D4-270'), (16, 'D4-300'), (17, 'D4-320'), (19, 'D6-280'), (20, 'D6-350'), (21, 'D6-435'), (22, 'D6-480'), (23, 'D8A1'), (24, 'D8A2'), (25, 'D8A6'), (26, 'D9A2'), (27, 'D11A'), (28, 'D11B'), (29, 'D11C'), (30, 'D13A'), (31, 'D13B'), (32, 'D13C')], default=1, max_length=40),
        ),
    ]
