# Generated by Django 4.1.2 on 2022-10-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_boat_num_engines_alter_boat_drive_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='engine',
            field=models.CharField(choices=[('1', 'D1-13'), ('2', 'D2-40'), ('3', 'D2-50'), ('4', 'D2-55'), ('5', 'D2-60'), ('6', 'D2-75'), ('7', 'D3-50'), ('8', 'D3-110'), ('9', 'D3-120'), ('10', 'D3-130'), ('11', 'D3-210'), ('12', 'D3-220'), ('13', 'D4-180'), ('14', 'D4-225'), ('15', 'D4-270'), ('16', 'D4-300'), ('17', 'D4-320'), ('19', 'D6-280'), ('20', 'D6-350'), ('21', 'D6-435'), ('22', 'D6-480'), ('23', 'D8A1'), ('24', 'D8A2'), ('25', 'D8A6'), ('26', 'D9A2'), ('27', 'D11A'), ('28', 'D11B'), ('29', 'D11C'), ('30', 'D13A'), ('31', 'D13B'), ('32', 'D13C')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='boat',
            name='num_engines',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
    ]
