# Generated by Django 4.1.2 on 2022-10-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_boat_engine_alter_boat_num_engines'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='hours',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
