# Generated by Django 4.1.2 on 2022-10-24 21:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_service_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Engine Oil'), ('2', 'Drive Oil'), ('3', 'Fuel Filters'), ('4', 'Air Filters'), ('5', 'Impellers'), ('6', 'Engine Anodes'), ('7', 'Drive Anodes'), ('8', 'Hull Anodes'), ('9', 'Air Coolers'), ('10', 'Heat Exchangers'), ('11', 'Oil Samples'), ('12', 'Coolant Test'), ('13', 'Coolant Swap')], max_length=13),
        ),
    ]
