# Generated by Django 4.1.2 on 2022-10-25 14:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_service_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', multiselectfield.db.fields.MultiSelectField(choices=[('3809721', '3809721 Volvo 3809721 Fuel Filter'), ('A026K278', 'A026K278 Onan A026K278 Fuel Filter'), ('E1C', 'E1C Camp E1C Engine Anode'), ('2040N-30', '2040N-30 Racor 2040N-30 Fuel Filter'), ('2010PM-OR', '2010PM-OR Racor 2010PM-OR Fuel Filter'), ('838929', '838929 Engine Anode'), ('10077K-SHW', '10077K-SHW Sherwood Impeller Kit'), ('21707132', '21707132 Volvo 21707132 Oil Filter'), ('0185-5835', '0185-5835 Cummins 0185-5835 Oil Filter'), ('93132', '93132 Star Brite 93132 Diesel Additive(32oz)'), ('3556610', '3556610 West Marine 3556610 - 60 Antifreeze(1 Gallon)'), ('23219274', '23219274 Volvo 23219274 Diesel Engine Oil(1 Gallon) 15w-40'), ('23005191', '23005191 Volvo 23005191 IPS Oil Filter'), ('949656', '949656 Volvo 949656 O Ring'), ('3593981', '3593981 Volvo 3593981 Anode Kit'), ('1141680', '1141680 Volvo 1141680 Synthetic Gear Oil: 75W-90 (1 Gallon)'), ('22030852', '22030852 Volvo 22030852 Oil Filter'), ('22030848', '22030848 Volvo 22030848 Oil Filter'), ('21718912', '21718912 Volvo 21718912 Fuel Filter'), ('3584145', '3584145 Volvo 3584145 CCV Filter'), ('21702999', '21702999 Volvo 21702999 Air Filter Insert')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['hours']},
        ),
        migrations.AddField(
            model_name='boat',
            name='parts',
            field=models.ManyToManyField(to='main_app.parts'),
        ),
    ]
