# Generated by Django 4.1.2 on 2022-10-25 15:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_parts_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='parts',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '3809721 Volvo 3809721 Fuel Filter'), ('2', 'A026K278 Onan A026K278 Fuel Filter'), ('3', 'E1C Camp E1C Engine Anode'), ('4', '2040N-30 Racor 2040N-30 Fuel Filter'), ('5', '2010PM-OR Racor 2010PM-OR Fuel Filter'), ('6', '838929 Engine Anode'), ('7', '10077K-SHW Sherwood Impeller Kit'), ('8', '21707132 Volvo 21707132 Oil Filter'), ('9', '0185-5835 Cummins 0185-5835 Oil Filter'), ('10', '93132 Star Brite 93132 Diesel Additive(32oz)'), ('11', '3556610 West Marine 3556610 - 60 Antifreeze(1 Gallon)'), ('12', '23219274 Volvo 23219274 Diesel Engine Oil(1 Gallon) 15w-40'), ('13', '23005191 Volvo 23005191 IPS Oil Filter'), ('14', '949656 Volvo 949656 O Ring'), ('15', '3593981 Volvo 3593981 Anode Kit'), ('16', '1141680 Volvo 1141680 Synthetic Gear Oil: 75W-90 (1 Gallon)'), ('17', '22030852 Volvo 22030852 Oil Filter'), ('18', '22030848 Volvo 22030848 Oil Filter'), ('19', '21718912 Volvo 21718912 Fuel Filter'), ('20', '3584145 Volvo 3584145 CCV Filter'), ('21', '21702999 Volvo 21702999 Air Filter Insert')], max_length=1000),
        ),
    ]
