# Generated by Django 4.1.2 on 2022-10-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_parts_parts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parts',
            new_name='Part',
        ),
    ]
